### ISSUE TITLE
Group capstone: set up our Kanban board

### ISSUE THREAD

**Issue by medaminedev66** [medaminedev66/javascript-capstone#21]
[Link](https://github.com/medaminedev66/javascript-capstone/projects/1)

We are 2 members of this team:
- Student A: Rida Arif
- Student B: Amine Smahi

**Comment by vichuge** [comment]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your PR messages are descriptive ✔️

## Aspects to improve ♻️

- [ ] When I click the URL to see the project in your description, it sends me to issues URL in place the project but copy-pasting the URL it works, please work on it. 🐶 
- [ ] It looks like the tasks are not assigned to anyone at this point, please, make sure the photo appears on each card to be sure it was assigned. Look at the example below:
![image](https://user-images.githubusercontent.com/20563252/132227395-a881beb5-8086-421e-9c20-e0ae87ecb6a4.png)

your project at this point:
![image](https://user-images.githubusercontent.com/20563252/132227449-b07d39b1-7177-4e29-a647-6649c5393093.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vichuge** [comment]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
